# Generated by Django 5.1.7 on 2025-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('url', models.URLField()),
                ('imagen', models.URLField()),
                ('tienda', models.CharField(max_length=100)),
            ],
        ),
    ]
