# Generated by Django 5.1.7 on 2025-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palas', '0002_pala_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pala',
            name='año_lanzamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='forma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='goma_nucleo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='material_caras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='material_marco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='resenas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pala',
            name='tecnologias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
